### PR TITLE
Use a custom CAS server for CAS integration tests

### PR DESCRIPTION
**Pull request by hannahwhy**
I would like Aker's tests to run with ActiveSupport 4.x -- there's nothing in Aker proper that won't work with it.  This is the most future-proof and direct way I could think of; other suggestions welcome.

Here's why I chose this route (from ff22b7291997cde692125efce31e7bf5cae6d9b7):

```
Justification:

1. Aker-Rails needs to officially support Rails 4.x.
2. To satisfy (1), Aker must work with ActiveSupport 4.x.
3. To satisfy (2), all of Aker's tests must pass with ActiveSupport 4.x.
4. The version of RubyCAS-Server that we use (RS) does not work with
   ActiveSupport 4.x.
5. The most recent version of RubyCAS-Server (RS') also does not work with
   ActiveSupport 4.x.
6. The startup procedure for RS' differs from the procedure for RS.
7. The problem with RS' and ActiveSupport 4.x looks like adjustments for
   changes in ActiveRecord 4.x.  I've looked into them, but didn't make
   much headway into solving the problem.
8. We do not need a database connection (or even an embedded database)
   to run Aker's CAS tests; we just need the server component of the CAS
   protocol.

The TestCasServer component (features/support/test_cas.rb) is an
implementation of CAS 2.0.  It does not use a database, and has only two
direct dependencies: sinatra and escape_utils.
```

Of course, there's one big issue with this: _there's no way to know if this CAS server actually implements CAS._

I've run `castanet`'s test suite against the CAS server in this commit, and it passes, but all that's saying is that something I wrote against Jasig's CAS server also works against a CAS server I wrote.  So it's worth something, but not much.  If we had a standalone CAS server compliance test suite, that'd help a lot -- but I can't find anything like that out there.

### CODE REVIEW

**Comment by rsutphin** [comment]
Why not use JA-SIG's CAS server for this also?

**Comment by hannahwhy** [comment]
I can say that the CAS server in this commit deviates from the CAS protocol in three ways:
1. It does not validate login tickets.
2. It does not prevent `/serviceValidate` from validating proxy tickets.
3. It does not prevent `/proxyValidate` from validating service tickets.

I'm not sure how much of a difference those deviations make.

**Comment by hannahwhy** [comment]
> Why not use JA-SIG's CAS server for this also?

Startup time, mostly.

Even when using the test authenticator, the Jasig CAS server takes 30-40 seconds to start; it's even worse when running in the NUBIC CI environment.  The Aker tests shut down the server after each scenario to ensure a clean state.  (Though I suppose they don't have to.)

**Comment by hannahwhy** [comment]
>  Why not use JA-SIG's CAS server for this also?

Actually, I'll look into using https://github.com/NUBIC/castanet-testing for that; we can measure the two approaches then.

**Comment by hannahwhy** [comment]
On a related note, I think that at some point we ought to remove CAS from Aker's test suite and do what Castanet does:

https://github.com/NUBIC/castanet/blob/master/features/support/env.rb#L15-L21

Provided that we establish a convention for acceptable and unacceptable credentials, we could then test Aker against any selection of CAS servers.  It also removes _all_ CAS-related dependencies from Aker's gem environment.

**Comment by rsutphin** [comment]
> The Aker tests shut down the server after each scenario to ensure a clean state. (Though I suppose they don't have to.)

It seems like it would be safe to convert Aker's CAS tests to all use the same set of users, then spin up the CAS server once per test run.

> Provided that we establish a convention for acceptable and unacceptable credentials, we could then test Aker against any selection of CAS servers. It also removes all CAS-related dependencies from Aker's gem environment.

Seems like a good idea to me.

**Comment by hannahwhy** [comment]
Superseded by #31.

**Pull request closed without merging**
